version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "15672:15672"
      - "5672:5672"


      
networks:
  web:
    name: web
    external: true
